avail_zone          = "ap-south-1a"
env_prefix          = "dev"
my_ip               = "*.*.*.*/32"
instance_type       = "t2.micro"
public_key_location = "~/.ssh/id_rsa.pub"
image_name          = "amzn2-ami-hvm-*-x86_64-gp2"
vpc_cidr_block      = "10.0.0.0/16"
subnet_cidr_block   = "10.0.1.0/24"